version: '3.4'
services:
  # set up postgres service
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hypersus
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d simple_bank" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_SOURCE: postgres://root:hypersus@postgres:5432/simple_bank?sslmode=disable
      GIN_MODE: release
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
