# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: deploy to container

on:
  push:
    branches: [ "main" ]

env:
  REGION_ID: 'cn-north-4'   # example: cn-north-4
  SWR_ORGANIZATION:  'zkproject'   # SWR 组织名
  IMAGE_NAME: 'simplebank'     # 镜像名称

jobs:
  swr-push:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Log in to huawei cloud swr
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }} 
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: '${{ env.REGION_ID }}'
      
      - name: Build, Tag, and Push Image to Huawei Cloud SWR
        id: push-image
        env:
          SWR_REGISTRY: swr.${{ env.REGION_ID }}.myhuaweicloud.com
          SWR_ORGANIZATION: ${{ env.SWR_ORGANIZATION }}
          IMAGE_TAG: ${{ github.sha }} # 镜像版本,这里是使用代码commitid sha值， 用户可以修改成自己需要的。
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          docker build -t $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG .
          docker push $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG
          echo "::set-output name=image::$SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG"
      